# fly.toml app configuration file generated for portafolio-web-backend-solitary-dawn-9347 on 2025-07-06T01:05:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portafolio-web-backend-solitary-dawn-9347'
primary_region = 'gru'

[build]

[env]
  PORT = "3000"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
